repos:
    -   repo: git://github.com/pre-commit/pre-commit-hooks
        rev: v2.1.0
        hooks:
        -   id: end-of-file-fixer
            exclude: ^docs/.*$
        -   id: trailing-whitespace
            exclude: README.md
        -   id: flake8

    -   repo: https://github.com/pre-commit/mirrors-yapf
        rev: v0.29.0
        hooks:
        -   id: yapf
            args: ['--style=.style.yapf', '--parallel', '--in-place']

    -   repo: git@github.com:humitos/mirrors-autoflake.git
        rev: v1.3
        hooks:
          -   id: autoflake
              args: ['--in-place', '--remove-all-unused-imports', '--ignore-init-module-imports']
